## Authorizations
# Uncomment out the merging for each enviornment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# enviornment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  group_base: ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - cn=admins,ou=groups,dc=test,dc=com
    - cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["moreMembers", "cn=users,ou=groups,dc=test,dc=com"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

## Environments

development:
  host: ldap.uchicago.edu
  port: 636
  attribute: uid
  base: ou=people,dc=uchicago,dc=edu
  ssl: true

test:
  host: ldap.uchicago.edu
  port: 636
  attribute: uid
  base: ou=people,dc=uchicago,dc=edu
  ssl: true

production:
  host: ldap.uchicago.edu
  port: 636
  attribute: uid
  base: ou=people,dc=uchicago,dc=edu
  ssl: true
